version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
  database:
    image: mariadb:10.5.8
    restart: always
    ports: 3306:3306
    volumes:
      - ./dump/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: admin
    
